language: objective-c

osx_image: xcode9.3
xcode_sdk: iphonesimulator
xcode_workspace: CF Apps.xcworkspace
xcode_scheme: CF Apps

before_install:
  - set -o pipefail
  - gem install cocoapods
  - pod install --repo-update

install: true

script:
  - travis_retry xcodebuild -workspace CF\ Apps.xcworkspace -scheme CF\ Apps -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE' build-for-testing test | xcpretty
